import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import { Link } from "react-router-dom";

const PrivacyPolicyContent = () => {
    return (
        <section>
            <Container fluid className="privacypolicy-section landing-page-bg d-flex align-items-center">
                <Row className='justify-content-center align-items-center'>
                    <h1 className="section-title text-center">Privacy Policy</h1>
                    <Col xs={12} md={10}>
                        <p className="text-white">Global Nation, Inc., its affiliates and subsidiaries (“Global Nation”), and its websites, applications including its subdomains together with all of their features and content and related or commonly-owned or operated websites, and applications, (the “Platform”), is made available by Global Nation.</p>

                        <h3>How This Privacy Policy Applies</h3>
                        <p className="text-white">Your privacy is very important to Global Nation, and in order to best protect your information, Global Nation has adopted this privacy policy (“Privacy Policy”), which applies to any and all information you submit to Global Nation in connection with your access to and/or use of the Platform. This Privacy Policy describes the information Global Nation collects from you through the Platform, how Global Nation uses that information, and its legal basis for doing so. It also covers whether and how that information may be shared and your rights and choices regarding the information you provide to Global Nation. It also covers whether and how that information may be shared and your rights and choices regarding such information.</p>

                        <p className="text-white">By using the Platform, you are accepting the practices described in this Privacy Policy (including new versions of this Privacy Policy when and as they go into effect), and Global Nation’s  <a href="/terms-of-service">Terms of Use</a>, which governs this Privacy Policy and contains all disclaimers of warranties and limitation of liabilities, and which constitutes a legally binding agreement between Global Nation and each individual, corporation, limited liability company, partnership, association, or other entity or party (a “Person”) that visits or uses the Platform (collectively, “Users,” and each, a “User”, “you” or “your”). Capitalized words not defined in this Privacy Policy are defined in the <a href="/terms-of-service">Terms of Use</a>.</p>

                        <h3>What Information Global Nation Collects and Receives</h3>
                        <p className="text-white">In order for you to use the Platform, Global Nation needs to collect and process certain information, which depending on how you use the Platform, may include:</p>
                        <ul>
                            <li className="text-white">Information you provide by using the Platform, such as by completing forms and/or registering on the Platform, such as your name, email address, mailing address, or telephone number, or by posting User Content to the extent the same is possible. We may ask for this information if you sign up for communications or contact us</li>
                            <li className="text-white">Details of any requests or transactions you make through the Platform. Global Nation may from time to time offer products for sale through the Platform and partner with certain third-party payment processors to facilitate in the transaction, in which case the payment information you submit will be collected and used by the payment processor in accordance with their respective privacy policies; </li>
                            <li className="text-white">Information that is not personally identifiable, but that relates to your usage of the Platform or that is aids in the proper functioning or improvement of the Platform, including: (i) times and dates and the extent of your usage of the Platform; (ii) time zone, language, screen resolution, and other usage preferences you select when using the Platform; (iii) device keyboard settings; (iv) usage history such as areas and pages within the Platform that you access or use and/or which buttons on the Platform you click on; (v) the search terms you entered into a search engine that may have led you to the Platform; (vi) the Internet service provider (ISP) or mobile platform you use, (vii) other device and Platform access information such as your browser type, operating system, Internet Protocol (IP) address, referring/exit pages, browsing and interaction habits, and other unique device identifiers; and (viii) specific geographical location of your device</li>
                            <li className="text-white">Communications you send to Global Nation, such as when you request support, submit comments or questions, or answer surveys or report a problem to Global Nation.</li>
                        </ul>
                        <p className="text-white">You can opt out of being included in Google Analytics at https://tools.google.com/dlpage/gaoptout, to the extent we use it. For more information about our use of data analytics to protect and improve our Platform, see Cookies and How We Utilize Them below.</p>

                        <p className="text-white">Global Nation also collects and maintain aggregated, anonymized, or pseudonymized information to protect the safety and security of the Platform, improve the Platform, or comply with its legal obligations.</p>

                        <p className="text-white">You may decline to provide Global Nation with some or all of your information. However, this will limit your ability to use the Platform.</p>

                        <h3>Types of Cookies Global Nation Utilizes</h3>
                        <p className="text-white">Global Nation uses the following types of cookies and other technologies:</p>
                        <ul>
                            <li className="text-white"><strong>Security:</strong> Global Nation secures the Platform with cookies that facilitate security features and allow Global Nation to detect activity that might violate the <a href="/terms-of-service">Terms of Use</a>, such as unauthorized access or activity.</li>
                            <li className="text-white"><strong>Localization:</strong> Some cookies help Global Nation provide localized experiences, such as displaying the Platform in the local language.</li>
                            <li className="text-white"><strong>Site Features and Services:</strong> Certain cookies provide greater functionality to the Platform and help Global Nation deliver our products and services.</li>
                            <li className="text-white"><strong>Performance:</strong> Global Nation uses performance cookies to help route traffic between servers and understand how the Platform is performing so Global Nation can provide Users with the best experience possible.</li>
                            <li className="text-white"><strong>Analytics and Research:</strong> Cookies and other technologies also help Global Nation to understand, improve, and research features and content on the Platform, such as by using Google Analytics, which you can opt out of at (https://tools.google.com/dlpage/gaoptout).</li>
                            <li className="text-white"><strong>Marketing and Online Behavioral Advertising:</strong> Cookies help us deliver targeted advertisements through web browsers and on social media platforms based on your activity on the Platform and to track the performance of those ads. In some cases, our partners may use cookies to provide us with information about your interactions with their services. Those third-party cookies would be subject to such third-party service’s privacy policies. The Self-Regulatory Program for Online Behavioral Advertising program provides consumers with the ability to opt-out of having their online behavior recorded and used for advertising purposes. Visit (http://optout.aboutads.info/) to opt out of having your online behavior collected for advertising purposes.</li>
                        </ul>

                        <h3>Limiting or Blocking Cookies and Our Do Not Track Policy</h3>
                        <p className="text-white">Your browser may give you the ability to control cookies, which may depend on the type of cookie, and browsers can be set to reject browser cookies. However, blocking or deleting cookies may prevent you from using most of the Platform.</p>
                        <p className="text-white">Some browsers have “do not track” features that allow you to tell a website not to track you. These features are not all uniform. If you block cookies, certain features on the Platform may not work. If you block or reject cookies, not all of the tracking described in this Privacy Policy will necessarily stop.</p>
                        <p className="text-white">Note that certain options you select are specific to certain browsers and devices.</p>

                        <h3>Web Beacons</h3>
                        <p className="text-white">The Platform may contain electronic images known as web beacons (sometimes called single-pixel gifs) and are used along with cookies to compile aggregated statistics to analyze how the Platform is used.</p>
                        <p className="text-white">Global Nation uses third parties to gather information about how you and others use the Platform.  For example, Global Nation will know how many Users access a specific page and what Platform Content they clicked on. Global Nation uses this aggregated information to understand and optimize how the Platform is used.</p>

                        <h3>Social Media Plug-ins</h3>
                        <p className="text-white">Global Nation may implement the use of certain social media plug-ins (e.g., Facebook, Twitter, YouTube) to allow you to communicate with such services and interact (e.g., “like” or “comment”) with various Platform content. The social media plug-in, if and when implemented, will enable a direct communication between your end user device and the servers of the applicable social media provider, allowing the applicable social media provider to communicate with you and collect information about you browsing the Platform. This processing is based on Article 6, Section 1(f) of the EU general data protection regulation 2016/679 (“GDPR”) and represents Global Nation’s legitimate interest to improve the User experience and to optimize those services and functionalities offered via the Platform.  If you decide to use a social media plug-in that Global Nation implements on the Platform, Global Nation may transfer your personal data, whether or not you have a registered user account with the applicable social media provider. Global Nation is not responsible for the content and the data collection on respective third-party websites or apps and that Global Nation neither controls the extent of personally information collected by the respective plug-in provider nor knows the processing’s purpose or the period your personally information will be retained. For further information as to how and for what purpose certain social network providers process your data, please see the relevant privacy policies of the three main social network providers, and their notification when you connect to the social network in question.</p>
                        <ul>
                            <li className="text-white"><strong>Facebook:</strong> Facebook, Inc., Attention: Privacy Operations, 1601 Willow Road, Menlo Park, California 94025, USA (https://www.facebook.com/policy.php)</li>
                            <li className="text-white"><strong>Twitter:</strong> Twitter, Inc., Attention: Privacy Policy Inquiry, 1355 Market Street, Suite 900 San Francisco, California 94103, USA (https://twitter.com/en/privacy)</li>
                            <li className="text-white"><strong>YouTube:</strong> Google LLC d/b/a YouTube, 901 Cherry Avenue, San Bruno, California 94066, USA (https://policies.google.com/privacy)</li>
                        </ul>

                        <h3>How Global Nation Uses the Information It Collects</h3>
                        <p className="text-white">Global Nation uses the information it collects for the following purposes:</p>
                        <ul>
                            <li className="text-white">To protect the Platform</li>
                            <li className="text-white">To enable Global Nation to provide you and other Users with the Platform, and to improve and promote the Platform and services</li>
                            <li className="text-white">To address inquiries and respond to customer service requests, questions, and comments</li>
                            <li className="text-white">To contact you with newsletters, offers, promotions, and other product specials or to customize your experience on the Platform</li>
                            <li className="text-white">To track and analyze use of the Platform and Global Nation’s services, such as to identify trends, conduct data analysis, and determine the effectiveness of marketing and promotion efforts, and other service offerings, so that Global Nation can improve how its performance and provide Users with the best experience possible</li>
                            <li className="text-white">To maintain security and to enforce the <a href="/terms-of-service">Terms of Use</a> and comply with applicable law</li>
                            <li className="text-white">For other purposes that Global Nation believes are necessary to protect its rights and the rights of others, or as otherwise described to you at the time of collection.</li>
                        </ul>

                        <h3>California Users</h3>
                        <p className="text-white">Under California Civil Code Section 1798.83, California customers are entitled to request information relating to whether a business has disclosed personal information to any third parties for those third parties’ direct marketing purposes. As explained elsewhere in this Privacy Policy, Global Nation will not sell or transfer your personal information to any third-party companies for their direct marketing purposes without your consent. California Users who wish to request further information about Global Nation’s compliance with this statute or who have questions more generally about the Privacy Policy and Global Nation’s privacy commitments to its Users should not hesitate to contact Global Nation at <a className="mailcolor" href="mailto:info@globalnation.tv">info@globalnation.tv</a>.</p>
                        

                        <h3>European Union Users</h3>
                        <p className="text-white">European Union data protection law requires a “lawful basis” for collecting and retaining personal information from citizens or residents of the European Economic Area. Global Nation’s lawful bases include:</p>
                        <ul>
                            <li className="text-white"><strong>Consent:</strong> In certain cases, you have affirmatively provided Global Nation with your consent to collect your personal data for a specific purpose, such as providing your name and email address when you sign up for communications or register for an Account.</li>
                            <li className="text-white"><strong>Contract:</strong> Global Nation may need your personal data to comply with contractual obligations to deliver the Platform, such as fulfilling subscriptions or transactions made through the Platform.</li>
                            <li className="text-white"><strong>Legal Obligations:</strong> Sometimes the law requires the collection and use of your data, such as applicable tax laws may require Global Nation to retain records of payments made through the Platform.</li>
                            <li className="text-white"><strong>Legitimate Interests:</strong> This is a technical term that means Global Nation has a good and fair reason to use your data and in ways which do not harm your interests and rights, such as to pursue Global Nation’s legitimate interests in a way that might reasonably be expected as part of running its business and that does not materially impact your rights, freedom, or interests. For example, Global Nation uses identity, device, and location information to prevent fraud and abuse and to keep the Platform secure, may also send you promotional communications about the Platform and services subject to your right to opt out, analyze how Users interact with the Platform so Global Nation can understand better what elements do or do not work well, thereby facilitating improvements and developments in the quality of the online experience for all Users.</li>
                        </ul>

                        <h3>How Global Nation Shares the Information It Collects</h3>
                        <h4 className="italic">Information That is Publicly Accessible</h4>
                        <p className="text-white">When you post User Content, all other Users will be able to view such User Content, subject to your security or viewability settings, along with your name and username that you provide when posting the User Content to the Interactive Areas. Users should not post to Interactive Areas any information, including, without limitation, personal information, that they do not want to be publicly accessible or viewable.</p>
                        

                        <h3>How Global Nation Shares the Information It Collects</h3>
                        <h4 className="italic">Information That is Publicly Accessible</h4>
                        <p className="text-white">When you post User Content, all other Users will be able to view such User Content, subject to your security or viewability settings, along with your name and username that you provide when posting the User Content to the Interactive Areas. Users should not post to Interactive Areas any information, including, without limitation, personal information, that they do not want to be publicly accessible or viewable.</p>
                        <h4 className="italic">Information Global Nation Never Shares Publicly</h4>
                        <p className="text-white">The following personal information is never publicly displayed or revealed to other Users:</p>
                        <ul>
                            <li className="text-white">Your name</li>
                            <li className="text-white">The date you register for any services Global Nation provides through the Platform</li>
                            <li className="text-white">Your email address, IP address, mailing address, or phone number</li>
                            <li className="text-white">Any other identity verification information or documentation</li>
                            <li className="text-white">Any payment information you provide and Communications you send to Global Nation</li>
                        </ul>

                        <h4 className="italic">Information Global Nation Shares with Trusted Third-Party Service Providers</h4>
                        <p className="text-white">Global Nation may share certain information pertaining to you with certain trusted third-party service providers to help provide, improve, promote, or protect the Platform, such as when Global Nation partners with payment processors or use services to help manage ads on other websites. When Global Nation shares data with third-party services to help deliver the Platform and Global Nation’s services, Global Nation requires those service providers use your information only for the purposes Global Nation has authorized and protect your personal information at least to the same standards Global Nation does. Global Nation may also share information that is aggregated and anonymized in a way that it does not directly identify you.</p>

                        <h4 className="italic">Information Global Nation Shares to Protect Global Nation and Comply with the Law</h4>
                        <p className="text-white">Global Nation reserves the right to disclose information Global Nation collects from or about you when doing so is reasonably necessary to comply with the law or law enforcement, to prevent fraud or abuse, or to protect Global Nation’s legal rights, property, or the safety of Global Nation, Users, or others. You hereby authorize Global Nation to share or disclose your personal information, including, without limitation, any content, records, or electronic communications of any kind, when Global Nation determines, in its sole discretion, that the disclosure of such information is necessary to identify, contact, or bring legal action against you if and to the extent:</p>
                        <ul>
                            <li className="text-white">You are or may be violating the <a href="/terms-of-service">Terms of Use</a> or this Privacy Policy</li>
                            <li className="text-white">You are interfering with the rights or property of Global Nation or a third party</li>
                            <li className="text-white">You are violating any applicable law, rule, or regulation</li>
                            <li className="text-white">Necessary or required by any applicable law, rule, or regulation and/or Requested by governmental authorities in the event of any investigation, act of terrorism, or instance of local, regional, or national emergency.</li>
                        </ul>
                        <p className="text-white">In the event that Global Nation is acquired by or merged with a third-party entity, or sells all or substantially all of its assets, Global Nation reserves the right, in any of these circumstances, to transfer or assign the information and content it has collected from Users as part of such merger, acquisition, sale, or other change of control. In the unlikely event of bankruptcy, insolvency, reorganization, receivership, or assignment for the benefit of creditors, or the application of laws or equitable principles affecting creditors’ rights generally, Global Nation may not be able to control how your personal information is treated, transferred, or used.</p>

                        <h3>Links to Other Platforms and Services</h3>
                        <p className="text-white">The Platform may include links to other websites or services whose privacy practices may differ from Global Nation’s privacy practices as described in this Privacy Policy. When you click or otherwise use a link to an external website or service, the privacy policy and data processing disclosures for that website or service govern.</p>

                        <h3>Data Retention</h3>
                        <p className="text-white">Global Nation will retain the information collected from or about you as long as necessary to provide you with the Platform or Global Nation’s services, or as otherwise set forth in this Privacy Policy, and to the extent set out in this Privacy Policy and as necessary to comply with Global Nation’s legal obligations, resolve disputes, enforce our agreements, and protect Global Nation’s legal rights. Additionally, Global Nation may retain indefinitely any aggregated, anonymized, or pseudonymized information collected, and may from time to time transfer or merge your information collected off-line to our online databases or store off-line information in an electronic format.</p>

                        <h3>Cross-Border Data Transfers</h3>
                        <p className="text-white">Global Nation is based in the United States so your information will be collected and processed in the United States, which has its own laws governing data protection and access to it, including by the government. If you reside outside of the United States, be advised that the rules that protect your personal information under United States federal, state, and local law may differ from those of your home country.</p>
                        <p className="text-white">With respect to any personal information that may be originally collected and stored in the European Economic Area, if and when Global Nation transfers your personal information to countries outside the European Economic Area, it will do so under the Commission’s model contracts for the transfer of personal information to third countries (i.e., standard contractual clauses) pursuant to 2004/915/EC or 2010/87/EU (as appropriate).  For a copy of these Standard Contractual Clauses, please contact Global Nation at <a className="mailcolor" href="mailto:info@globalnation.tv">info@globalnation.tv</a>.</p>

                        <h3>Children’s Privacy</h3>
                        <p className="text-white">The Platform is not directed to children under the age of 13.  Nonetheless, the privacy of children is of the utmost importance, and Global Nation is committed to complying with the federal Children’s Online Privacy Protection Act (COPPA). Global Nation does not knowingly collect, use, or disclose personal information from children under the age of thirteen (13). If Global Nation ever discovers that it has inadvertently collected personal information from a child under the age of thirteen (13) on or through the Platform, Global Nation will delete it from its records as soon as possible. If you are a parent or legal guardian of a child under the age of thirteen (13) and believe that Global Nation has collected personal information from your child, please email us at <a className="mailcolor" href="mailto:info@globalnation.tv">info@globalnation.tv</a>, and Global Nation will take steps to delete such personal information from its records as soon as possible.</p>

                        <h3>Accessing Your Information</h3>
                        <p className="text-white">Users residing in certain countries, including citizens or residents of the European Economic Area, are afforded certain rights regarding their personal information. Except where an exception or exemption applies, these rights include the ability to access, correct, and request deletion of such User’s personal information. Even after you request Global Nation deletes your personal information, Global Nation may retain certain information as required by law or as necessary for its legitimate business purposes.</p>
                        <p className="text-white">More specifically, these Users have the following rights:</p>
                        <ul>
                        <li className="text-white">The right to require free of charge (i) confirmation of whether Global Nation processes your personal information and (ii) access to a copy of the personal information retained</li>
                        <li className="text-white">The right to request proper rectification, removal or restriction of your personal information</li>
                        <li className="text-white">Where processing of your personal information is either based on your consent or necessary for the performance of a contract with you and processing is carried out by automated means, the right to receive the personal information concerning you in a structured, commonly used and machine-readable format or to have your personal information transmitted directly to another company, where technically feasible (data portability)</li>
                        <li className="text-white">Where the processing of your personal information is based on your consent, the right to withdraw your consent at any time without impact to data processing activities that have taken place before such withdrawal or to any other existing legal justification of the processing activity in question</li>
                        <li className="text-white">The right not to be subject to any automatic individual decisions which produces legal effects on you or similarly significantly affects you and The right to take legal actions in relation to any breach of your rights regarding the processing of the personal information, as well as to lodge complaints before the competent data protection regulators.</li>
                        </ul>

                        <p className="text-white">As far as Global Nation processes your personal information on the basis of its legitimate interests, you can object to processing at any time. You can find a detailed description of Global Nation’s processing activities and the legal basis herein. If you object to such processing, Global Nation will ask you to state the grounds of your objection to examine the processing of your personal information and decide whether to adjust the processing accordingly.</p>

                        <h3>Email Notifications</h3>
                        <p className="text-white">Global Nation want to communicate with you only if you want to hear from us. Global Nation will send you email relating to your transactions on or through the Platform. You may also elect to receive certain marketing email communications, in accordance with your preferences, and from which you may opt out at any time by adjusting your notification settings. Global Nation will also send you service-related announcements when and as necessary. Global Nation will try to keep emails to a minimum and give you the ability to opt in to any marketing communications.</p>
                        <p className="text-white">Global Nation maintains a strict no-spam policy. Global Nation will not use false or misleading subjects or email addresses, identify the message as an advertisement in a reasonable way, include Global Nation’s physical address, monitor third-party email marketing services for compliance, honor opt-out/unsubscribe requests quickly, and allow Users to unsubscribe by using the link at the bottom of each email. If you are having problems unsubscribing, contact Global Nation at <a className="mailcolor" href="mailto:info@globalnation.tv">info@globalnation.tv</a> by forwarding the email communication and including the word “Unsubscribe” in the subject line and Global Nation will use reasonable efforts to remove you within seven (7) business days. Please note that Global Nation will not process any unsubscribe requests submitted as direct replies to any newsletter.</p>

                        <h3>Security</h3>
                        <p className="text-white">Global Nation takes security seriously, and the security of your personal data is important to us. Global Nation follows industry-standard practices to protect the data Global Nation collects and maintains, including using Transport Layer Security (TLS) to encrypt information as it travels over the Internet.</p>
                        <p className="text-white">However, the Internet is, by nature, not a secure environment and the nature of security risks is constantly evolving as are the technical and organizational industry standards relating to management of those risks. While Global Nation strives to keep current our security technology and will review, refine, and upgrade its security technology as Global Nation deems appropriate based on new tools that may become available in the future, the complete security of any information collected, stored or used by Global Nation cannot therefore be guaranteed. In the unlikely event that an unauthorized third-party compromises Global Nation’s security measures, Global Nation will not be responsible for any damages directly or indirectly caused by an unauthorized third party’s ability to view, use, or disseminate such information.</p>

                        <h3>Updates to this Privacy Policy</h3>
                        <p className="text-white">Global Nation may change the terms of this Privacy Policy at any time. Whenever Global Nation makes a material change, Global Nation will post on the Platform or send you an email. The effective date of the most recent version of this Privacy Policy will appear at the top of this page. New versions of this Privacy Policy will never apply retroactively.</p>

                        <h3>Contact</h3>
                        <p className="text-white">Questions or comments about this Privacy Policy should be sent by email to <a className="mailcolor" href="mailto:info@globalnation.tv">info@globalnation.tv</a> or mail to Operator’s Address.</p>

                    </Col>
                </Row>
            </Container>
        </section>
    );
};

export default PrivacyPolicyContent;